name: Lint Markdown

on: [push]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      # Pull the repository
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      # Setup NodeJS
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20
          check-latest: true
          cache-dependency-path: "package-lock.json"

      - name: "Install Node Dependencies"
        run: npm install

      - name: "Run Linter"
        run: npm exec markdownlint '**/*.md' --ignore node_modules
