name: Lint Markdown

on: [push]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    # Pull the repository
    - name: "Checkout Repository"
      uses: actions/checkout@v4

    # Setup NodeJS
    - name: "Setup Node"
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        node-version: 20
        check-latest: true

    - name: "Run Linter"
      run: npx markdownlint --ignore node_modules .
